### ISSUE TITLE
Cannot read properties of undefined (reading 'id') when running npm run set-up-content

### ISSUE THREAD

**Issue by rsalim0** [a-trost/fizzi#2]
D:\fiz\fizzy\node_modules\@prismicio\src\WriteClient.ts:401
                const masterLocale = repository.languages.find((lang) => lang.is_master)!.id
                                                                                       ^

TypeError: Cannot read properties of undefined (reading 'id')
    at WriteClient.migrateCreateDocuments (D:\fiz\fizzy\node_modules\@prismicio\src\WriteClient.ts:401:74)   
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at WriteClient.migrate (D:\fiz\fizzy\node_modules\@prismicio\src\WriteClient.ts:295:9)
    at main (D:\fiz\fizzy\set-up-content.ts:49:3)

Node.js v21.6.0
PS D:\fiz\fizzy>

**Comment by rsalim0** [comment]
Adding language to be English -United States

**Comment by rutaganda-salim** [comment]
complete
